print()
print("Задача №1 Арифметичні операції")
print()
variable_1 = input("Введіть перше число - ")
variable_2 = input("Введіть друге число - ")
print()
print("Сума:",int(variable_1) + int(variable_2))
print("Різниця:",int(variable_1) - int(variable_2))
print("Добуток:",int(variable_1) * int(variable_2))
print("Частка:",int(variable_1) / int(variable_2))
print()
print()
print("Задача №2 Залишок від ділення")
print()
variable_1 = input("Введіть перше число - ")
variable_2 = input("Введіть друге число - ")
print()
print("Залишок від ділення першого числа на друге:", int(variable_1) % int(variable_2))
print()
print()
print("Задача №3 Цілочисельне ділення")
print()
variable_1 = input("Введіть перше число - ")
variable_2 = input("Введіть друге число - ")
print()
print("Скільки разів перше число ділиться на друге без залишку:",int(variable_1) // int(variable_2))
print()
print()
print("Задача №4 Перетворення стрічки у число")
print()
year = int(input("Введіть свій рік народження - "))
print(year)
print(type(year))
print()
print()
print("Задача №5 Стрічкова конкатенація + математика")
print()
number_1 = input("Введіть перше число - ")
number_2 = input("Введіть друге число - ")
print(int(number_1) + int(number_2))
print(number_1 + number_2)
print()
print()
print("Задача №6 Вік користувача")
print()
year_1 = input("Введіть свій рік народження - ")
name = input("Введіть своє ім'я - ")
year_3 = input("Введіть який зараз рік - ")
print()
print("Ваше ім'я - ",name)
print("Ваш вік - ",int(year_3) - int(year_1),"років")
print()
print("Задача №7 Перевод з цельсія в фаренгейт")
print()
degree = input("Введіть кількість градусів у цельсіях - ")
print("Це дорівнює кількості градусів у фарінгейтах - ",(int(degree)*9/5+32))
print()
print()
print("Задача №8 Перевод з фаренгейта в цельсій")
print()
degree = input("Введіть кількість градусів у фарінгейтах - ")
print("Це дорівнює кількості градусів у цельсіях - ",(int(degree)-32)*5/9)
print()
print()
print("Задача №9 Теорема Піфагора")
print()
number = input("Введіть довжину катета - ")
number2 = int(number)**2 + int(number)**2
print("Довжина гіпотенузи - ",int(number2)**(1/2))
print()
print()
print("Задача №10 Школярі та яблука")
print()
number_1 = input("Введіть кількість школярів(ціле число, додатнє, не перевищує 10000) - ")
number_2 = input("Введіть кількість яблук(ціле число, додатнє, не перевищує 10000)  - ")
print()
print("Кожному школяреві дістанеться порівну яблук- ",int(number_2) // int(number_1))
print("Залишок яблук в кошику - ",int(number_2) % int(number_1))
print()
print()
print("Задача №11 Магазин канцелярських товарів")
print()
number_1 = input("Введіть скільки олівців купив Вася ,але не більше 109 - ")
number_2 = input("Введіть скільки ручок купив Вася ,але не більше 109 - ")
number_3 = input("Введіть скільки фломастерів купив Вася ,але не більше 109 - ")
print()
print("Загальна сума канцелярських товарів - ",int(number_1)*3 + int(number_2)*5 + int(number_3)*12,"грн.")
print()
print()
print("Задача №12 Циферблад")
print()
time = input("Cкільки хвилин пройшло з початку доби ? - ")
print("На годиннику зараз  - ",(int(time) // 60),':',(int(time) % 60))
print()
print()
print("Задача №13 Журавлики")
print()
number = input("Cкільки журавликів було зроблено всього ? - ")
print("Катя зробила - ",(int(number) * 2/3))
print("Петро зроби  - ",(int(number) / 3/2))
print("Сергій зробив  - ",(int(number) /3/2))
print()
print()
print("Задача №14 Податки")
print()
number1 = input("Введіть суму зарплати за три місяці  - ")
number2 = input("Введіть відсоток ЄП до сплати - ")
number3 = int(number1) * int(number2) /100
print()
print("ЄП,грн  - ",number3)
print("ЄСВ,грн  - 4422")
print("Загальн сума податків за три місяці (ЄП + ЄСВ),грн - ", number3 + 4422)
print()
print()
